const pool = require("./")

async function createInventoryImagesTable() {
  try {
    console.log("Starting to create inventory_images table...")
    
    // Check if table already exists
    const checkTable = await pool.query(
      "SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'inventory_images')"
    )
    
    if (checkTable.rows[0].exists) {
      console.log("inventory_images table already exists")
      return
    }
    
    // Create the inventory_images table
    const createTableSQL = `
    CREATE TABLE IF NOT EXISTS public.inventory_images (
      image_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
      inventory_id INTEGER NOT NULL,
      image_path VARCHAR NOT NULL,
      thumbnail_path VARCHAR NOT NULL,
      primary_image BOOLEAN DEFAULT FALSE,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT inventory_images_pkey PRIMARY KEY (image_id),
      CONSTRAINT fk_inventory FOREIGN KEY (inventory_id)
        REFERENCES public.inventory (inv_id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
    )`
    
    await pool.query(createTableSQL)
    console.log("inventory_images table created successfully")
    
    process.exit(0)
  } catch (error) {
    console.error("Error creating inventory_images table:", error)
    process.exit(1)
  }
}

createInventoryImagesTable() 